# Generated by Django 5.2.8 on 2025-11-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when the task was assigned to a user', null=True),
        ),
    ]
