# Generated by Django 5.2.8 on 2026-01-19 08:30

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Team name', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Team description', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(blank=True, help_text='Manager assigned to this team', limit_choices_to={'role': 'manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(help_text='Unique employee ID', max_length=50, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('date_of_joining', models.DateField(help_text='Date when employee joined')),
                ('status', models.CharField(choices=[('active', 'Active'), ('on_leave', 'On Leave'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('position', models.CharField(blank=True, help_text='Job position/title', max_length=255, null=True)),
                ('base_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Base salary in INR (₹)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='Associated user account', on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, help_text='Team/Department assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employees.team')),
            ],
            options={
                'verbose_name': 'Employee Profile',
                'verbose_name_plural': 'Employee Profiles',
                'ordering': ['-date_of_joining'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Attendance date')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('half_day', 'Half Day'), ('leave', 'On Leave')], default='present', max_length=20)),
                ('check_in', models.TimeField(blank=True, help_text='Check-in time', null=True)),
                ('check_out', models.TimeField(blank=True, help_text='Check-out time', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marked_by', models.ForeignKey(help_text='User who marked this attendance (for admin override)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendances', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(help_text='Employee for this attendance record', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='employees.employeeprofile')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['-date'],
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(help_text='Month (1-12)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year', models.IntegerField(help_text='Year')),
                ('base_salary', models.DecimalField(decimal_places=2, help_text='Base salary in INR (₹)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('days_worked', models.IntegerField(default=0, help_text='Number of days worked', validators=[django.core.validators.MinValueValidator(0)])),
                ('days_present', models.IntegerField(default=0, help_text='Days present', validators=[django.core.validators.MinValueValidator(0)])),
                ('days_absent', models.IntegerField(default=0, help_text='Days absent', validators=[django.core.validators.MinValueValidator(0)])),
                ('days_on_leave', models.IntegerField(default=0, help_text='Days on leave', validators=[django.core.validators.MinValueValidator(0)])),
                ('deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Deductions in INR (₹)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('bonuses', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Bonuses in INR (₹)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('final_pay', models.DecimalField(decimal_places=2, help_text='Final payable amount in INR (₹)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processed', 'Processed'), ('paid', 'Paid')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(help_text='Employee for this payroll record', on_delete=django.db.models.deletion.CASCADE, related_name='payroll_records', to='employees.employeeprofile')),
            ],
            options={
                'verbose_name': 'Payroll',
                'verbose_name_plural': 'Payroll Records',
                'ordering': ['-year', '-month'],
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
    ]
