# Generated by Django 5.2.8 on 2026-01-19 08:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(default='WorkForge HR', help_text='Organization name', max_length=255)),
                ('organization_logo', models.FileField(blank=True, help_text='Organization logo', null=True, upload_to='logos/')),
                ('company_address', models.TextField(blank=True, help_text='Company address', null=True)),
                ('working_days', models.CharField(choices=[('mon-fri', 'Monday - Friday'), ('mon-sat', 'Monday - Saturday'), ('mon-sun', 'Monday - Sunday'), ('custom', 'Custom')], default='mon-fri', help_text='Default working days', max_length=50)),
                ('custom_working_days', models.JSONField(blank=True, default=list, help_text='Custom working days (if custom selected)')),
                ('default_working_hours_start', models.TimeField(default='09:00', help_text='Default work start time')),
                ('default_working_hours_end', models.TimeField(default='18:00', help_text='Default work end time')),
                ('currency', models.CharField(default='INR', help_text='Currency code', max_length=10)),
                ('currency_symbol', models.CharField(default='₹', help_text='Currency symbol', max_length=5)),
                ('working_days_per_month', models.IntegerField(default=26, help_text='Default working days per month', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organization Settings',
                'verbose_name_plural': 'Organization Settings',
            },
        ),
        migrations.CreateModel(
            name='SystemPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_self_registration', models.BooleanField(default=False, help_text='Allow users to self-register')),
                ('session_timeout_minutes', models.IntegerField(default=60, help_text='Session timeout in minutes', validators=[django.core.validators.MinValueValidator(5)])),
                ('force_password_reset', models.BooleanField(default=False, help_text='Force password reset on next login')),
                ('theme_mode', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto')], default='light', help_text='Theme mode', max_length=10)),
                ('date_format', models.CharField(choices=[('DD/MM/YYYY', 'DD/MM/YYYY'), ('MM/DD/YYYY', 'MM/DD/YYYY'), ('YYYY-MM-DD', 'YYYY-MM-DD')], default='DD/MM/YYYY', help_text='Date format', max_length=20)),
                ('timezone', models.CharField(default='Asia/Kolkata', help_text='Timezone', max_length=50)),
                ('enable_notifications', models.BooleanField(default=True, help_text='Enable system notifications')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Preferences',
                'verbose_name_plural': 'System Preferences',
            },
        ),
    ]
